# Font
font_family                  JetBrainsMono Nerd Font
bold_font                    auto
italic_font                  auto
bold_italic_font             auto
font_size                    12.5
disable_ligatures            never

# Cursor
cursor_shape                 block
cursor_blink_interval        0
cursor_stop_blinking_after   0

# Cursor trail
cursor_trail                 15
cursor_trail_decay           0.07 0.18
cursor_trail_start_threshold 1

# Performance
input_delay                  0
repaint_delay                5
sync_to_monitor              yes
wayland_enable_ime           no

# Window
window_padding_width         4
single_window_padding_width  4
placement_strategy           center
remember_window_size         yes
initial_window_width         1100
initial_window_height        700
confirm_os_window_close      -1

# GNOME Wayland titlebar behavior
wayland_titlebar_color       system

# Borders
window_border_width          1pt
draw_minimal_borders         yes

# Scrollback
scrollback_lines             10000
scrollback_pager_history_size 64

# Scrollbar
scrollbar                    scrolled-and-hovered
scrollbar_width              0.5
scrollbar_hover_width        0.9
scrollbar_handle_opacity     0.55
scrollbar_track_opacity      0.0
scrollbar_track_hover_opacity 0.12
scrollbar_radius             0.25

# Mouse and links
mouse_hide_wait              1.0
detect_urls                  yes
url_style                    curly
underline_hyperlinks         hover
show_hyperlink_targets       yes
open_url_with                default

# Selection and paste safety
copy_on_select               yes
strip_trailing_spaces        smart
paste_actions                quote-urls-at-prompt,confirm,confirm-if-large

# Shell integration
shell_integration            enabled
notify_on_cmd_finish         invisible 15

# Security
allow_remote_control         no
allow_hyperlinks             yes
clipboard_control            write-clipboard write-primary read-clipboard-ask read-primary-ask

background_opacity           1.0
background_blur              0


# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME
