return {
    "coc-json",
    "coc-lua",
    "coc-tsserver",
    "coc-html",
    "coc-css",
    "coc-pyright",
    "coc-java",
    "coc-snippets",
    "coc-pairs",
    "coc-svelte",
    "coc-csharp-ls",
    "@yaegassy/coc-tailwindcss3",
    "coc-rust-analyzer",
}
